### ISSUE TITLE
Use sync-type for service resource fetch

### ISSUE THREAD

**Issue by fmigneault** [Ouranosinc/Magpie#107]
Relates to #42 (fetch service resources) and PR #104 

Regarding comments starting at (detail of problem / envisioned solution) : 
https://github.com/Ouranosinc/Magpie/pull/104#issuecomment-425252071

This feature becomes **BLOCKER** for OGC.
`/processes/{id}` will need to be automatically updated with new processes so that read/write permissions be updated as required.

Will resolve any 'fetching' variations of common `ServiceAPI` type for `geoserver-api`, `project-api` and `twitcher-api` .

**Comment by dbyrns** [comment]
Thank you @fmigneault for reporting this issue. @davidcaron you can start working on that since its for OGC and is flagged as blocker.

**Comment by davidcaron** [comment]
I prepared #104 to make sure I uniquely identify services by their id instead of their name and type.

I'm pretty sure that [this line change](https://github.com/Ouranosinc/Magpie/pull/104/commits/73580a9e8acbec5638bd98b3568a7b08c2de59a) is all we needed to make it work with the new table column. I'll test when your migrations are ready.

**Comment by fmigneault** [comment]
ready with branch https://github.com/Ouranosinc/Magpie/tree/service-api-ponctual-permissions

**Comment by fmigneault** [comment]
resolved via PR #110
