### ISSUE TITLE
ESGF x509 certificates

### ISSUE THREAD

**Issue by tomLandry** [Ouranosinc/Magpie#145]
As referenced here: https://github.com/bird-house/birdy/issues/105

Just a quick question to see how / if Magpie could be used to fetch the certificates, and how that could be used for our uses cases.

**Comment by fmigneault** [comment]
@tomLandry not sure it is Magpie's role, more probably Twitcher. Magpie only manages the permissions of corresponding users/groups on resources, Twitcher enforces them with the proxy.

**Comment by dbyrns** [comment]
I think that twitcher already has some pieces of code for that... Or was it Phoenix?

**Comment by fmigneault** [comment]
Yes it does, not sure what is/isn't implemented related to this and birdy's issues.

**Comment by dbyrns** [comment]
I guess that twitcher is able to inject a certificate while proxying a WPS, but since birdy is expected to call a WPS directly as a client, that functionnality would be helpful to be built in directly.
In any case, Magpie should also be supported in Birdy. 
Then I guess that for Birdy it does make more sense to support both Magpie and x509 certificate than supporting only a Magpie that somehow would support x509 certificates. Magpie would become an undesirable dependency.

**Comment by fmigneault** [comment]
I agree, better that birdy supports it itself since it accesses the services directly.
Otherwise, it would as a new functionality to Magpie, that it wouldn't even use itself...
Is there use cases to have Magpie support in birdy?

**Comment by dbyrns** [comment]
Birdy is a small wps python client. It must be able to use PAVICS components and thus must support magpie as an AuthZ  provider. But by support I don't mean that it must know magpie. Like owslib was "supporting" magpie by allowing custom cookie, I think that birdy could do the same.

**Comment by tomLandry** [comment]
Cool, thanks for the discussion.
