### ISSUE TITLE
[Feature] Is it possible to edit the anonymous user?

### ISSUE THREAD

**Issue by tlvu** [Ouranosinc/Magpie#443]
**Is your feature request related to a problem? Please describe.**
From https://github.com/bird-house/birdhouse-deploy/pull/182#issuecomment-884376408 I found out our anonymous user has a duplicated email with a real user.

So I wonder if it's possible to edit the anonymous user via the UI or it will have to be a direct DB update?

Error when trying to update via the UI:
```
[2021-07-23 17:50:53,028] ERROR      [ThreadPoolExecutor-0_0][magpie.ui.utils] Unexpected API error under UI operation. [{'path': '/users/anonymous', 'url': 'https://lvupavicsdev.ouranos.ca/magpie/users/anonymous', 'detail': 'Targeted user update not allowed by requesting user.', 'method': 'PATCH', 'user_name': 'anonymous', 'code': 403, 'type': 'application/json'}]
```

Magpie-3.12.0 (from https://github.com/bird-house/birdhouse-deploy/tree/1.13.12)

**Describe the solution you'd like**
A recommended way to update the anonymous user.

**Comment by fmigneault** [comment]
Anonymous user should not be modified because its email is enforced with the value based on the name, unless the current email is not the expected value and you plan to change it back to the expected one.

https://github.com/Ouranosinc/Magpie/blob/35f03158a5fcaea2cad31e08733307346479fd13/magpie/constants.py#L97-L99

Both the API and UI do not allow edit of anonymous. It must be done directly with the DB. This is by design. 
I noticed that email-edit button is enabled, but it shouldn't in this case based on API behaviour.

**Comment by tlvu** [comment]
> Both the API and UI do not allow edit of anonymous. It must be done directly with the DB. This is by design.
> Something like such?
> 
> ```shell
> echo "update users set email = 'anoynymous@mail.com' where user_name = 'anonymous'" | \
> docker exec -i postgres-magpie psql -U $POSTGRES_MAGPIE_USERNAME magpiedb > /tmp/result.txt
> ```

Confirmed the direct SQL above works to edit user's email directly in DB, closing this issue.
